home:
    path:     /
    host:     "%domain_consumer%"
    defaults: { _controller: AppWebBundle:Index:index }

consumer_category:
    resource: "@AppWebBundle/Controller/CategoryController.php"
    type:     annotation
    prefix: /category
    
consumer_item:
    resource: "@AppWebBundle/Controller/ItemController.php"
    type:     annotation
    prefix: /item
    
page_category:
    resource: "@AppWebBundle/Controller/ComponentController.php"
    type:     annotation
    prefix: /components
    
page_store:
    resource: "@AppWebBundle/Controller/StoreController.php"
    type:     annotation
    prefix: /store
    
page_keyword:
    resource: "@AppWebBundle/Controller/KeywordController.php"
    type:     annotation
    prefix: /keyword
    
page_cart:
    resource: "@AppWebBundle/Controller/AccountController.php"
    type:     annotation
    prefix: /account