imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    translator.class: Funddy\Bundle\JsTranslationsBundle\ReadableTranslator\SymfonyReadableTranslator

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources:
        - 'AppFrontBundle::fields.html.twig'
    globals:
        productUploadDir: %products_upload_dir%
        rootDir: %kernel.root_dir%
        app_web_user: @app.web.user
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    node: /usr/bin/nodejs
    use_controller: false
    bundles:        [ AppFrontBundle, AppWebBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
            presets:
                my_variable: "#000"
        scssphp:
            apply_to: "\.scss$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# nzo url encryptor configuration
nzo_url_encryptor:
    secret: "%secret%"

gregwar_image: ~

funddy_js_translations:
    languages: [en,de]
    domains: [messages]

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: '.tinymce'
    language: %locale%
    theme:
        simple:
            theme: "modern"

endroid_qr_code:
    size: 150
    padding: 20
    extension: gif
    error_correction_level: high
    foreground_color: { r: 0, g: 0, b: 0, a: 0 }
    background_color: { r: 255, g: 255, b: 255, a: 0 }
    label: "Scan The Code"
    label_font_size: 12
fos_user:
    db_driver: orm
    firewall_name: social
    user_class: App\FrontBundle\Entity\Consumer

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: oauth_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [default]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "email, public_profile"
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        item_thumb :
            quality : 75
            filters :
                thumbnail  : { size : [171, 230], mode : outbound }
                
        item_large :
            quality : 75
            filters :
                thumbnail  : { size : [387, 493], mode : outbound }
                
        item_larger :
            quality : 100
            filters :
                thumbnail  : { size : [750, 1000], mode : outbound }
                
        banner :
            quality : 75
            filters :
                thumbnail  : { size : [760, 375], mode : outbound }
                
        popular_cat :
            quality : 75
            filters :
                thumbnail  : { size : [293, 302], mode : outbound }
                
        store :
            quality : 75
            filters :
                thumbnail  : { size : [300, 250], mode : outbound }
                
        user :
            quality : 75
            filters :
                thumbnail  : { size : [208, 228], mode : outbound }
                
        offer :
            quality : 75
            filters :
                thumbnail  : { size : [300, 250], mode : outbound }
