security:

    encoders:
        App\FrontBundle\Entity\User: sha512
        harsh:
            algorithm: bcrypt
            cost: 15
    providers:
        consumer:
            entity: { class: 'App\FrontBundle\Entity\Consumer' }
        admin:
            entity: { class: 'App\FrontBundle\Entity\Admin' }
        vendor:
            entity: { class: 'App\FrontBundle\Entity\Vendor' }
        fos_userbundle:
            id: fos_user.user_provider.username_email
        api_key_user_provider:
            id: api_key_user_provider
    acl:
        connection: default
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin:
            anonymous: ~
            http_basic: ~
            provider: admin
            pattern: ^/
            host: "%domain_admin%"
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /dashboard
                always_use_default_target_path: false
                use_referer: true
                csrf_provider: security.csrf.token_manager
                
            logout:
                path:   /logout
                target: /login

            remember_me:
                key:      "%secret%"
                lifetime: 604800 # one week in seconds
                path: /
                domain: "%domain_admin%"
        vendor:
            anonymous: ~
            http_basic: ~
            provider: vendor
            pattern: ^/
            host: "%domain_vendor%"
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /items
                always_use_default_target_path: false
                use_referer: true
                csrf_provider: security.csrf.token_manager
                
            logout:
                path:   /logout
                target: /login

            remember_me:
                key:      "%secret%"
                lifetime: 604800 # one week in seconds
                path: /
                domain: "%domain_vendor%"
        default:
            anonymous: ~
            http_basic: ~
            provider: consumer
            pattern: ^/
            host: "%domain_consumer%"
            form_login:
                login_path: /account/login
                check_path: /login_check
                default_target_path: /account
                always_use_default_target_path: true
                use_referer: true
                csrf_provider: security.csrf.token_manager
            oauth:
                resource_owners:
                    facebook: facebook_login_check
                    google: google_login_check
                login_path:        /account/login
                default_target_path: /account
                failure_path:      /account/login
                use_referer: true
                
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: oauth_user_provider    
            logout:
                path:   /account/logout
                target: /account/login

            remember_me:
                key:      "%secret%"
                lifetime: 604800 # one week in seconds
                path: /
                domain: "%domain_consumer%"
                    
    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/[a-z]+, roles: ROLE_ADMIN, host: %domain_admin% }
      - { path: ^/[a-z]+, roles: ROLE_VENDOR, host: %domain_vendor% }
      - { path: ^/account/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/forgot/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/reset/*, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/email/validate, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/activate/[a-z0-9]+, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/cart, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/wishlist, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: %domain_consumer% }
      - { path: ^/account/[a-z]+, roles: ROLE_CONSUMER, host: %domain_consumer% }
      - { path: ^/item/[0-9]+/buy_now, roles: ROLE_CONSUMER, host: %domain_consumer% }
      - { path: ^/anon/cart/[0-9]+, roles: ROLE_CONSUMER, host: %domain_consumer% }