set_lang:
    path:  /lang/{_locale}/{route}
    defaults: { _controller: AppFrontBundle:Default:setlang }
    requirements:
        _locale: de|en
    
app_front_consumer_login_check:
    path:     /login_check
    host:     "%domain_consumer%"
    defaults: { _controller: AppFrontBundle:User:logincheck }
    
app_front_consumer_logout:
    host:     "%domain_consumer%"
    path: /account/logout
    
########################################################

app_front_admin_login:
    path:     /login
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:User:login }
    
app_front_admin_login_check:
    path:     /login_check
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:User:logincheck }
    
app_front_admin_logout:
    host:     "%domain_admin%"
    path: /logout
    
app_front_admin_profile:
    host:     "%domain_admin%"
    path: /profile
    defaults: { _controller: AppFrontBundle:Admin:profile}
    
app_front_admin_home:
    path:     /dashboard
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:dashboard}
    
app_front_admin_region:
    path:     /region
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:region}

admin_region_actions:
    resource: "@AppFrontBundle/Controller/RegionController.php"
    type:     annotation
    prefix: /region
    
admin_location_actions:
    resource: "@AppFrontBundle/Controller/LocationController.php"
    type:     annotation
    prefix: /location

app_front_admin_category:
    path:     /categroy
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:category}

admin_category_actions:
    resource: "@AppFrontBundle/Controller/CategoryController.php"
    type:     annotation
    prefix: /category
    
app_front_admin_product:
    path:     /product
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:product}
    
admin_product_actions:
    resource: "@AppFrontBundle/Controller/ProductController.php"
    type:     annotation
    prefix: /product
       
admin_item_actions:
    resource: "@AppFrontBundle/Controller/ItemController.php"
    type:     annotation
    prefix: /item  
    
admin_keyword_pages:
    resource: "@AppFrontBundle/Controller/KeywordController.php"
    type:     annotation
    prefix: /keyword

app_front_admin_brand:
    path:     /brand
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:brand}

admin_brand_actions:
    resource: "@AppFrontBundle/Controller/BrandController.php"
    type:     annotation
    prefix: /brand

app_front_admin_variant:
    path:     /variant
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:variant}
    
admin_variant_actions:
    resource: "@AppFrontBundle/Controller/VariantController.php"
    type:     annotation
    prefix: /variant

app_front_admin_banner:
    path:     /banner
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:banner}

admin_banner_actions:
    resource: "@AppFrontBundle/Controller/BannerController.php"
    type:     annotation
    prefix: /banner
    
app_front_admin_vendor:
    path:     /vendor
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:vendor}

admin_vendor_actions:
    resource: "@AppFrontBundle/Controller/VendorController.php"
    type:     annotation
    prefix: /vendor

app_front_admin_consumer:
    path:     /consumer
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:consumer}
    
admin_consumer_actions:
    resource: "@AppFrontBundle/Controller/ConsumerController.php"
    type:     annotation
    prefix: /consumer


app_front_admin_order:
    path:     /order
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:order}
    
order_actions:
    resource: "@AppFrontBundle/Controller/OrderController.php"
    type:     annotation
    prefix: /order

order_item_actions:
    resource: "@AppFrontBundle/Controller/OrderItemController.php"
    type:     annotation
    prefix: /order/items
    
app_front_admin_offer:
    path:     /offer
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:offer}
    
offer_actions:
    resource: "@AppFrontBundle/Controller/OfferController.php"
    type:     annotation
    prefix: /offer
    
app_front_admin_config:
    path:     /config
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:config}

config_actions:
    resource: "@AppFrontBundle/Controller/ConfigController.php"
    type:     annotation
    prefix: /config
    
app_front_admin_invoice:
    path:     /invoice
    host:     "%domain_admin%"
    defaults: { _controller: AppFrontBundle:Admin:invoice}

invoice_actions:
    resource: "@AppFrontBundle/Controller/InvoiceController.php"
    type:     annotation
    prefix: /invoice
    
#########################################################

app_front_vendor_login:
    path:     /login
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:login }
    
app_front_vendor_login_check:
    path:     /login_check
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:logincheck }
    
app_front_vendor_logout:
    host:     "%domain_vendor%"
    path: /logout
    
app_front_vendor_profile:
    host:     "%domain_vendor%"
    path: /profile
    defaults: { _controller: AppFrontBundle:Vendor:profile}
    
app_front_vendor_pwd_reset:
    host:     "%domain_vendor%"
    path: /reset
    defaults: { _controller: AppFrontBundle:Vendor:password}
    
app_front_vendor_home:
    path:     /dashboard
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:index}
    
app_front_vendor_items:
    path:     /items
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:items}
    
app_front_vendor_items_preview:
    path:     /items/{id}/preview
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:itempreview}
    
app_front_vendor_orders:
    path:     /orders
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:orders}
    
app_front_vendor_orders_result:
    path:     /orders/{id}/result
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:ordersResult}

vendor_item_autocomplete:
    path:     /autocomplete/items
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:itemautocomplete}

stock_actions:
    resource: "@AppFrontBundle/Controller/StockController.php"
    type:     annotation
    prefix: /stock
    
stockentry_actions:
    resource: "@AppFrontBundle/Controller/StockEntryController.php"
    type:     annotation
    prefix: /stockentry
    
vendoritem_actions:
    resource: "@AppFrontBundle/Controller/VendorItemController.php"
    type:     annotation
    prefix: /items
    
app_front_vendor_invoice:
    path:     /invoices
    host:     "%domain_vendor%"
    defaults: { _controller: AppFrontBundle:Vendor:invoices}
    
cart_actions:
    resource: "@AppFrontBundle/Controller/CartController.php"
    type:     annotation
    prefix: /cart