parameters:
    app.front.entity.consumer.class: 'App\FrontBundle\Entity\Consumer'
    app.front.entity.admin.class: 'App\FrontBundle\Entity\Admin'
    app.language.class: 'App\FrontBundle\EventListener\LocaleListener'
    app.user.language.class: 'App\FrontBundle\EventListener\UserLocaleListener'
    app.voter.product.class: 'App\FrontBundle\Security\Authorization\ProductVoter'
    app.security.success.handler.class: 'App\FrontBundle\Handler\AuthenticationSuccessHandler'
    app.security.failure.handler.class: 'App\FrontBundle\Handler\AuthenticationFailureHandler'
  
services:
    app.repository.abstract:
      abstract: true
      factory_service: doctrine.orm.entity_manager
      factory_method: getRepository

    logout_listener:
      class: App\FrontBundle\EventListener\LogoutListener

    app.front.entity.consumer:
      class: %app.front.entity.consumer.class%

    app.front.entity.admin:
      class: %app.front.entity.admin.class%

    app.front.locale_listener:
      class: %app.language.class%
      arguments: ["%kernel.default_locale%"]
      tags:
        - { name: kernel.event_subscriber }

    app.front.user_locale_listener:
      class: %app.user.language.class%
      arguments: ["@session"]
      tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    entity.user.listener:
      class: App\FrontBundle\EventListener\Entity\UserListener
      arguments: ['@service_container']
      tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    security.access.post_voter:
      class: %app.voter.product.class%
      public: false
      arguments: ['@service_container']
      tags:
          - { name: security.voter }

    security.authentication.success_handler:
      class:  %app.security.success.handler.class%
      arguments:  ["@security.http_utils", {}, "@service_container"]
      tags:
          - { name: 'monolog.logger', channel: 'security' }

    security.authentication.failure_handler:
      class:  %app.security.failure.handler.class%
      arguments:  ["@kernel", "@security.http_utils", {}, "@service_container"]
      tags:
          - { name: 'monolog.logger', channel: 'security' }
    
    app.kernel_listener:
        class: App\FrontBundle\EventListener\KernelListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }
            
  #  security.authentication.logout_handler:
  #    class:  App\FrontBundle\EventListener\LogoutListener
  #    tags:
  #        - { name: 'monolog.logger', channel: 'security' }

    api_key_user_provider:
          class: App\FrontBundle\Entity\UserRepository
          parent: app.repository.abstract
          arguments: [ App\FrontBundle\Entity\Consumer ]

    apikey_authenticator:
          class:  App\FrontBundle\Security\ApiKeyAuthenticator
          public: false

    app.front.datatable.region:
          class: App\FrontBundle\Datatables\RegionDatatable
          parent: sg_datatables.datatable.abstract
          
    app.front.datatable.location:
          class: App\FrontBundle\Datatables\LocationDatatable
          parent: sg_datatables.datatable.abstract
          
    app.front.datatable.category:
          class: App\FrontBundle\Datatables\CategoryDatatable
          parent: sg_datatables.datatable.abstract
          
    app.front.datatable.product:
          class: App\FrontBundle\Datatables\ProductDatatable
          parent: sg_datatables.datatable.abstract
          
    app.front.datatable.item:
         class: App\FrontBundle\Datatables\ItemDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.brand:
         class: App\FrontBundle\Datatables\BrandDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.variant:
         class: App\FrontBundle\Datatables\VariantTypeDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.banner:
         class: App\FrontBundle\Datatables\BannerDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.vendor:
         class: App\FrontBundle\Datatables\UserDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.stock:
         class: App\FrontBundle\Datatables\StockDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.stockentry:
         class: App\FrontBundle\Datatables\StockEntryDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.purchase:
         class: App\FrontBundle\Datatables\PurchaseDatatable
         parent: sg_datatables.datatable.abstract
         
    app.front.datatable.purchaseitem:
         class: App\FrontBundle\Datatables\PurchaseItemDatatable
         parent: sg_datatables.datatable.abstract
    
    app.front.datatable.vendorItem:
        class: App\FrontBundle\Datatables\VendorItemDatatable
        parent: sg_datatables.datatable.abstract
        
    app.front.datatable.offer:
        class: App\FrontBundle\Datatables\OfferDatatable
        parent: sg_datatables.datatable.abstract
        
    app.front.datatable.config:
        class: App\FrontBundle\Datatables\ConfigDatatable
        parent: sg_datatables.datatable.abstract
        
    app.front.datatable.invoice:
        class: App\FrontBundle\Datatables\InvoiceDatatable
        parent: sg_datatables.datatable.abstract
    
    app.front.datatable.invoiceitem:
         class: App\FrontBundle\Datatables\InvoiceItemDatatable
         parent: sg_datatables.datatable.abstract